### ISSUE TITLE
Metodo eliminar cuenta

### ISSUE THREAD

**Issue by DaniGalicia** [DaniGalicia/Sistema-Contable#4]
Agregar un boton el cual al ser presionado debe eliminar la cuenta seleccionada de la tabla.

Dicho metodo debe validar que halla una cuenta seleccionada.

**Comment by KathyaMaria** [comment]
Este esto se supone que no lo haremos verdad?

**Comment by DaniGalicia** [comment]
Si lo haremos, porque este no se refiere a eliminar cuenta de la base de datos sino eliminarla de la tabla (quitarla de la tabla)

**Comment by KathyaMaria** [comment]
ohh okay jaja se noto que leo va esta bien me atuve porque crei que era el eliminar de la cuenta de la base y dije eso no lo haremos pero no habia leido , sorry manana despues de porgra lo hago :)

**Comment by KathyaMaria** [comment]
ya esta me avisa si esta bien .

**Comment by DaniGalicia** [comment]
El metodo funciona, pero tiene un bug. Cuando la hay solo una fila en la tabla no la elimina.
Motivo: Recordar que en una  tabla las filas se cuentan desde cero no de 1

Ayuda: Cuando no hay una fila seleccionada el metodo getSelectedRow devuelve -1

**Comment by DaniGalicia** [comment]
El metodo funciona correctamente.
