### ISSUE TITLE
Crear cuenta

### ISSUE THREAD

**Issue by DaniGalicia** [DaniGalicia/Sistema-Contable#6]
Si la cuenta no debera ser creada.
Agregar un checkbox (crear). El cual al ser pulsado debe ocultar el combobox y mostrar un textefield (en la misma posicion) para que se ingrese el nombre de la cuenta.

Al presionar el boton agregar se debera agregar la cuenta (con su respectiva transaccion), agregarlo a la lista del combo y seguir el proceso normal para agregar una transaccion a la tabla

**Comment by JoseReneEscobar** [comment]
hey pero a la lista del combo no? eso  al final sera con la base d datos o solo es para efectos de prueba?

**Comment by JoseReneEscobar** [comment]
ah y me confunde eso de "si la cuenta no debera ser creada"

**Comment by JoseReneEscobar** [comment]
Finalizado.
